void main(){
  String sehir = "Çanakkale";
  String ulke = "Türkiye";
  int telefon = 2122121212;
  int postaKodu = 34340;
  String email = "murathan.1999@gmail.com";
  String meslek = "Bilgisayar Mühendisliği";
  int stokMiktari = 168;
  String musteriAdi = "Murathan Karaca";
  double bakiye = 142.5;
  String dogumGunu = "24.04.1999";
  double maas = 8567.7;
  bool evlimi = true;
  String urunYorum = "Ürün 5 yıldızı hakediyor.";
  String odemeTarihi = "06.12.2022";
  bool odemeYaptimi = true;
  int siparisAdeti = 1050;
  String arabaModeli = "Ford";
  String kitapAdi = "Harry Potter Ateş Kadehi";
  String yayinlanmaTarihi = "08.07.2000";
  int indirimMiktari = 35;
  int odaSayisi = 10;
  double enlem = 41.1033246;
  double boylam = 28.9908487;
  String urunAdi = "Futbol Topu";
  double yemekFiyati = 35.5;
  String marka = "Nike";
  String muzikAdi = "lavinia";
  double videoSuresi = 20.15;
  double urunPuani = 4.2;
  String resimAdi = "Kaplumbağa Terbiyecisi";
  String dosyaFormati = ".doc";
  String renk = "yeşil";
  String renkKodu = "#f2f2f2";
  String telefonModeli = "One Plus Nord 10";
  String ekranBoyutu = "17 inç";
  double agirlik = 85.2;
  String ulusalGun= "29 Ekim Cumhuriyet Bayramı";
  String tatilGunu = "Haftasonu tatili";
  var rezervasyonTarihi = DateTime(2022, 12, 06, 12, 52);
  String sokakAdi = "Mandıracı 3. Sokak";
  String otobusHatti = "25E";
  int kalanDakika = 137;
  String takipKodu = "RQ3636363MY";
  String kuponSuresi = "48 Saat";
  String kuponKodu = "ST13MT120521";
  String faturaAdresi = "Çerkezköy OSB, 7. Cadde, No:114,, 59500 Çerkezköy/Tekirdağ";

  print("Şehir : $sehir");
  print("Ülke : $ulke");
  print("Telefon Numarası : +90$telefon");
  print("Posta Kodu : $postaKodu");
  print("Email : $email");
  print("Mesleği : $meslek");
  print("Stok Miktarı : $stokMiktari");
  print("Müşteri Adı : $musteriAdi");
  print("Bakiye : $bakiye");
  print("Doğum Günü : $dogumGunu");
  print("Maaşı : $maas");
  print("Evli mi, Bekar mı ? : $evlimi");
  print("Ürün Yorumu : $urunYorum");
  print("Ödeme Tarihi : $odemeTarihi");
  print("Ödeme Yapıldı mı ? : $odemeYaptimi");
  print("Sipariş Adeti : $siparisAdeti");
  print("Arabanın Modeli : $arabaModeli");
  print("Kitabın Adı : $kitapAdi");
  print("Yayınlanma Tarihi : $yayinlanmaTarihi");
  print("İndirim Miktarı : %$indirimMiktari");
  print("Oda Sayısı : $odaSayisi");
  print("Enlem : $enlem");
  print("Boylam : $boylam");
  print("Ürünün Adı : $urunAdi");
  print("Yemeğin Fiyatı : $yemekFiyati");
  print("Markası : $marka");
  print("Müziğin Adı : $muzikAdi");
  print("Video Süresi : $videoSuresi");
  print("Ürünün Puanı : $urunPuani");
  print("Resmin Adı : $resimAdi");
  print("Dosya Formatı : $dosyaFormati");
  print("Rengi : $renk");
  print("Renk Kodu : $renkKodu");
  print("Telefon Modeli : $telefonModeli");
  print("Ekran Boyutu : $ekranBoyutu");
  print("Ağırlığı : $agirlik");
  print("Ulusal Gün : $ulusalGun");
  print("Tatil Günü : $tatilGunu");
  print("Rezarvasyon Tarihi : $rezervasyonTarihi");
  print("Sokağın Adı : $sokakAdi");
  print("Otobüs Hattı : $otobusHatti");
  print("Kalan Dakika : $kalanDakika");
  print("Takip Kodu : $takipKodu");
  print("Kupon Süresi : $kuponSuresi");
  print("Kupon Kodu : $kuponKodu");
  print("Fatura Adresi : $faturaAdresi");
}